In [1]:
import pandas as pd

# Load data from berita_cnn.csv
df = pd.read_csv('berita_detik_sport_finance.csv')

In [2]:
# Display basic information about the dataset
print("Dataset shape:", df.shape)
df

Dataset shape: (200, 4)

,kategori,judul,isi_berita,url
0,Sport,Ketum KONI Tutup Program Sport Diplomacy Indon...,Ketua UmumKomite Olahraga Nasional Indonesia (...,https://sport.detik.com/g-sport/d-8666151/ketu...
1,Sport,"Usai Dilantik KONI, Ini Rencana Pengurus Pusat...",Pengurus Pusat Kickboxing Indonesia (PP KBI)pe...,https://sport.detik.com/sport-lain/d-8666068/u...
2,Sport,"Lina Hisage, Atlet Muda Potensial Cabor Tolak ...","Lina Hisage, atlet tolak peluru asal Wamena, P...",https://sport.detik.com/sport-lain/d-8666076/l...
3,Sport,Tim Equestrian Indonesia Turunkan 12 Atlet di ...,Timnas Equestrian Indonesiasudah bertolak ke J...,https://sport.detik.com/sport-lain/d-8665977/t...
4,Sport,Serunya 549 Siswa di Ciamis Adu Ketangkasan Lo...,Ciamis- Sebanyak 549 siswa dari 40 SD mengikut...,https://sport.detik.com/fotosport/d-8665222/se...
...,...,...,...,...
195,Finance,"Bea Cukai Gagalkan Penyelundupan 330 Kg Emas, ...",Direktorat Jenderal Bea dan Cukai (DJBC) Kemen...,https://finance.detik.com/berita-ekonomi-bisni...
196,Finance,"Ribuan Pegawai Kementerian PU Main Judol, Tran...",Ribuan pegawai Kementerian Pekerjaan Umum (PU)...,https://finance.detik.com/infrastruktur/d-8663...
197,Finance,Utang Luar Negeri RI Tembus Rp 8.004 T,Posisi Utang Luar Negeri (ULN) Indonesia pada ...,https://finance.detik.com/moneter/d-8663963/ut...
198,Finance,OJK Bentuk Bursa Mineral ICOMEX 2 Hari Lagi,Otoritas Jasa Keuangan (OJK) akan meresmikan I...,https://finance.detik.com/bursa-dan-valas/d-86...
199,Finance,Dirjen Bea Cukai Bicara Nasib Ratusan Pejabat ...,Direktorat Jenderal Bea dan Cukai (DJBC) Kemen...,https://finance.detik.com/berita-ekonomi-bisni...

In [3]:
print("\nDataset info:")
df.info()

Dataset info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   kategori    200 non-null    object
 1   judul       200 non-null    object
 2   isi_berita  200 non-null    object
 3   url         200 non-null    object
dtypes: object(4)
memory usage: 6.4+ KB

In [4]:
# Tampilkan data "isi"
df['isi_berita']

0      Ketua UmumKomite Olahraga Nasional Indonesia (...
1      Pengurus Pusat Kickboxing Indonesia (PP KBI)pe...
2      Lina Hisage, atlet tolak peluru asal Wamena, P...
3      Timnas Equestrian Indonesiasudah bertolak ke J...
4      Ciamis- Sebanyak 549 siswa dari 40 SD mengikut...
                             ...
195    Direktorat Jenderal Bea dan Cukai (DJBC) Kemen...
196    Ribuan pegawai Kementerian Pekerjaan Umum (PU)...
197    Posisi Utang Luar Negeri (ULN) Indonesia pada ...
198    Otoritas Jasa Keuangan (OJK) akan meresmikan I...
199    Direktorat Jenderal Bea dan Cukai (DJBC) Kemen...
Name: isi_berita, Length: 200, dtype: object

In [5]:
# Hapus baris dengan Missing Value di 'isi'
df.dropna(subset=['isi_berita'], inplace=True)

# Hapus data duplikat
df.drop_duplicates(inplace=True)

In [6]:
import re

# Fungsi untuk membersihkan teks
def clean_text(text):
    text = text.lower() # Ubah ke huruf kecil
    text = re.sub(r'[^\w\s]', '', text) # Hapus tanda baca
    text = re.sub(r'\d+', '', text) # Hapus nomor
    return text

# Terapkan pembersihan ke kolom 'isi'
df['cleaned_isi'] = df['isi_berita'].apply(clean_text)

# Tampilkan DataFrame
display(df[['isi_berita', 'cleaned_isi']].head())

,isi_berita,cleaned_isi
0,Ketua UmumKomite Olahraga Nasional Indonesia (...,ketua umumkomite olahraga nasional indonesia k...
1,Pengurus Pusat Kickboxing Indonesia (PP KBI)pe...,pengurus pusat kickboxing indonesia pp kbiperi...
2,"Lina Hisage, atlet tolak peluru asal Wamena, P...",lina hisage atlet tolak peluru asal wamena pap...
3,Timnas Equestrian Indonesiasudah bertolak ke J...,timnas equestrian indonesiasudah bertolak ke j...
4,Ciamis- Sebanyak 549 siswa dari 40 SD mengikut...,ciamis sebanyak siswa dari sd mengikuti lomb...

In [7]:
from nltk.tokenize import word_tokenize
import nltk
nltk.download('punkt')
nltk.download('punkt_tab') 

# Fungsi untuk melakukan tokenisasi
def tokenize_text(text):
    return word_tokenize(text)

# Terapkan tokenisasi ke kolom 'cleaned_isi'
df['tokenized_isi'] = df['cleaned_isi'].apply(tokenize_text)

# Tampilkan DataFrame dengan kolom hasil tokenisasi
display(df[['cleaned_isi', 'tokenized_isi']].head())

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\faisal\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\faisal\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

,cleaned_isi,tokenized_isi
0,ketua umumkomite olahraga nasional indonesia k...,"[ketua, umumkomite, olahraga, nasional, indone..."
1,pengurus pusat kickboxing indonesia pp kbiperi...,"[pengurus, pusat, kickboxing, indonesia, pp, k..."
2,lina hisage atlet tolak peluru asal wamena pap...,"[lina, hisage, atlet, tolak, peluru, asal, wam..."
3,timnas equestrian indonesiasudah bertolak ke j...,"[timnas, equestrian, indonesiasudah, bertolak,..."
4,ciamis sebanyak siswa dari sd mengikuti lomb...,"[ciamis, sebanyak, siswa, dari, sd, mengikuti,..."

In [8]:
from nltk.corpus import stopwords
nltk.download('stopwords')

# Dapatkan Stop Word bahasa Indonesia
list_stopwords = set(stopwords.words('indonesian'))

# Fungsi untuk menghapus stop words
def remove_stopwords(tokens):
    return [word for word in tokens if word not in list_stopwords]

# Terapkan penghapusan Stop Word ke kolom 'tokenized_isi'
df['stopwords_removed_isi'] = df['tokenized_isi'].apply(remove_stopwords)

# Tampilkan DataFrame
display(df[['tokenized_isi', 'stopwords_removed_isi']].head())

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\faisal\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

,tokenized_isi,stopwords_removed_isi
0,"[ketua, umumkomite, olahraga, nasional, indone...","[ketua, umumkomite, olahraga, nasional, indone..."
1,"[pengurus, pusat, kickboxing, indonesia, pp, k...","[pengurus, pusat, kickboxing, indonesia, pp, k..."
2,"[lina, hisage, atlet, tolak, peluru, asal, wam...","[lina, hisage, atlet, tolak, peluru, wamena, p..."
3,"[timnas, equestrian, indonesiasudah, bertolak,...","[timnas, equestrian, indonesiasudah, bertolak,..."
4,"[ciamis, sebanyak, siswa, dari, sd, mengikuti,...","[ciamis, siswa, sd, mengikuti, lomba, olahraga..."

In [9]:
!pip install Sastrawi

Requirement already satisfied: Sastrawi in c:\users\faisal\envwebmining39\lib\site-packages (1.0.1)

WARNING: You are using pip version 22.0.4; however, version 26.0.1 is available.
You should consider upgrading via the 'C:\Users\faisal\envWebmining39\Scripts\python.exe -m pip install --upgrade pip' command.

In [10]:
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

# Buat stemmer
factory = StemmerFactory()
stemmer = factory.create_stemmer()

# Fungsi untuk melakukan stemming
def stem_tokens(tokens):
    return [stemmer.stem(token) for token in tokens]

# Terapkan stemming ke kolom 'stopwords_removed_isi'
df['stemmed_isi'] = df['stopwords_removed_isi'].apply(stem_tokens)

# Function to find and format stemmed word changes
def get_stemming_changes(original_tokens, stemmed_tokens):
    changes = []
    for original, stemmed in zip(original_tokens, stemmed_tokens):
        if original != stemmed:
            changes.append(f"{original} : {stemmed}")
    return changes

# Dapatkan semua perubahan stemming dari kolom 'stopwords_removed_isi' dan 'stemmed_isi'
all_changes = []
for index, row in df.iterrows():
    all_changes.extend(get_stemming_changes(row['stopwords_removed_isi'], row['stemmed_isi']))

# Dapatkan perubahan unik dan urutkan
unique_changes = sorted(list(set(all_changes)))

# Cetak perubahan unik
print("Kata-kata yang mengalami stemming:")
for change in unique_changes:
    print(change)

# Tampilkan DataFrame
display(df[['stopwords_removed_isi', 'stemmed_isi']].head())

Kata-kata yang mengalami stemming:
acaranya : acara
acuan : acu
acuannya : acu
ajakan : aja
ajukan : aju
akibatnya : akibat
aksinya : aksi
alasan : alas
alasannya : alas
aliran : alir
alunan : alun
anaknya : anak
ancaman : ancam
andalan : andal
andalkan : andal
anggapan : anggap
anggaran : anggar
angkanya : angka
angkatan : angkat
angkutan : angkut
antaralainâ : antaralain
antrean : antre
antrian : antri
antusiasmenya : antusiasme
apapun : apa
apresiasinya : apresiasi
arahan : arah
arahkan : arah
areanya : area
asapi : asap
asian : asi
asuhan : asuh
atasannya : atas
atletnya : atlet
aturan : atur
aturannya : atur
bagikan : bagi
bagimu : bagi
baginya : bagi
bahunya : bahu
balapan : balap
balapannya : balap
balapku : balap
balapnya : balap
bali : bal
baliknya : balik
bangunan : bangun
bantuan : bantu
banyaknya : banyak
baranya : bara
barisan : baris
barunya : baru
batangan : batang
batasan : batas
batasnya : batas
bawaan : bawa
bawahnya : bawah
bebannya : beban
bebernya : beber
bekasi : bekas
belajar : ajar
belajarnya : ajar
belakangnya : belakang
belasan : bas
benakku : benak
bepergian : pergi
beradaptasi : adaptasi
beragam : agam
beraktivitas : aktivitas
beralih : alih
berangsur : angsur
berasa : asa
berasal : asal
berasumsi : asumsi
berbagi : bagi
berbanding : banding
berbasis : bas
berbeda : beda
berbekal : bekal
berbelanja : belanja
berbelok : belok
berbicara : bicara
berbincang : bincang
berbuat : buat
berburu : buru
bercanda : canda
bercorak : corak
berdampak : dampak
berdasarkan : dasar
berdaya : daya
berdesakan : desa
berdialog : dialog
berdiri : diri
berdisiplin : disiplin
berdiskusi : diskus
berdomisili : domisili
berdua : dua
berdurasi : durasi
bereaksi : reaksi
berebut : rebut
beredar : edar
beregu : regu
beregunya : regu
berenangnya : renang
berencana : rencana
beretika : etika
berfokus : fokus
bergabung : gabung
bergaji : gaji
berganda : ganda
berganti : ganti
bergantian : ganti
bergantung : gantung
bergaris : gar
bergengsi : gengsi
bergerak : gerak
bergeser : geser
bergirang : girang
bergizi : gizi
bergulir : gulir
berguna : guna
bergurau : gurau
berhadapan : hadap
berhak : hak
berharap : harap
berharga : harga
berhasil : hasil
berhenti : henti
berikutâ : ikut
berinovasi : inovasi
berinvestasi : investasi
berisikan : risi
beristirahat : istirahat
berjalan : jalan
berjangka : jangka
berjarak : jarak
berjaya : jaya
berjenjang : jenjang
berjuang : juang
berkaitan : kait
berkala : kala
berkapasitas : kapasitas
berkekuatan : kuat
berkelanjutan : lanjut
berkembang : kembang
berkembangnya : kembang
berkenalan : nal
berkendara : kendara
berkewajiban : wajib
berkiprah : kiprah
berkisar : kisar
berkolaborasi : kolaborasi
berkomentar : komentar
berkomitmen : komitmen
berkompetisi : kompetisi
berkomunikasi : komunikasi
berkontribusi : kontribusi
berkoordinasi : koordinasi
berkualitas : kualitas
berkuda : kuda
berkumpul : kumpul
berkurang : kurang
berkurangnya : kurang
berkutat : kutat
berlabel : label
berlaga : laga
berlaku : laku
berlangganan : langgan
berlangsungnya : langsung
berlanjut : lanjut
berlapis : lap
berlari : lari
berlatih : latih
berlayar : layar
berlomba : lomba
bermain : main
bermakna : makna
bermasalah : masalah
bermental : mental
berminat : minat
bermodal : modal
bermutu : mutu
bernama : nama
bernasib : nasib
bernaung : naung
bernegara : negara
bernilai : nila
bernostalgia : nostalgia
beroperasi : operasi
berorientasi : orientasi
berpangku : pangku
berpartisipasi : partisipasi
berpasangan : pasang
berpeluang : peluang
berpendapat : dapat
berpengalaman : alam
berpengaruh : pengaruh
berpenghasilan : hasil
berperingkat : peringkat
berpesan : pesan
berpihak : pihak
berpijak : pijak
berpikir : pikir
berpindah : pindah
berpotensi : potensi
berprestasi : prestasi
berpuas : puas
bersaing : saing
bersalah : salah
bersamaan : sama
bersamanya : sama
bersandar : sandar
bersandi : sandi
bersangkutan : sangkut
bersatu : satu
bersaudara : saudara
bersedia : sedia
berselang : selang
bersifat : sifat
bersikap : sikap
bersinergi : sinergi
berskala : skala
berspekulasi : spekulasi
berstandar : standar
berstatus : status
bersubsidi : subsidi
bersulang : sulang
bersyukur : syukur
bertahan : tahan
bertahap : tahap
bertalenta : talenta
bertambah : tambah
bertambahnya : tambah
bertanding : tanding
bertandingnya : tanding
bertanggung : tanggung
bertaruh : taruh
bertarung : tarung
bertekad : tekad
bertema : tema
bertemu : temu
bertemunya : temu
bertepatan : tepat
berterima : terima
bertetangga : tetangga
bertindak : tindak
bertolak : tolak
bertransaksi : transaksi
bertugas : tugas
bertujuan : tuju
bertukar : tukar
bertumbuh : tumbuh
bertumpu : tumpu
berubah : ubah
berujung : ujung
berukuran : ukur
berulang : ulang
beruntun : untun
beruntung : untung
berupaya : upaya
berusaha : usaha
berusia : usia
berwarna : warna
berwenang : wenang
besaran : besar
besarnya : besar
beserta : serta
besinya : besi
bicaranya : bicara
binaan : bina
bisingnya : bising
bisnisnya : bisnis
bobotnya : bobot
bolanya : bola
bonusnya : bonus
buatnya : buat
buktikan : bukti
bulanan : bulan
bumn_id : bumn id
bundaran : bundar
butuhkan : butuh
cabutan : cabut
cadangan : cadang
cakupan : cakup
campuran : campur
capaian : capai
catatan : catat
catatannya : catat
cicilan : cicil
cicilannya : cicil
contohnya : contoh
dadakan : dada
daerahnya : daerah
dalamnya : dalam
dampaknya : dampak
dananya : dana
dani : dan
dapatkan : dapat
dasarnya : dasar
debutan : debut
debutnya : debut
denganku : dengan
dengannya : dengan
depannya : depan
diabaikan : abai
diabet : abet
diadakan : ada
diadukan : adu
diajak : ajak
diajar : ajar
diajukan : aju
diakses : akses
diakumulasikan : akumulasi
dialami : alami
dialaminya : alam
dialihkan : alih
diamankan : aman
diambil : ambil
diambilnya : ambil
diamini : amin
diandalkan : andal
dianggap : anggap
diangkat : angkat
diangkut : angkut
diarahkan : arah
diasah : asah
diasian : asi
diatas : atas
diatur : atur
diawali : awal
dibaca : baca
dibagi : bagi
dibahas : bahas
dibanderol : banderol
dibanding : banding
dibandingkan : banding
dibangun : bangun
dibantu : bantu
dibarengi : bareng
dibatalkan : batal
dibawa : bawa
dibawah : bawah
dibayangi : bayang
dibayarkan : bayar
dibebankan : beban
dibeli : beli
dibenahi : benah
dibenarkan : benar
dibentuk : bentuk
diberangkatkan : berangkat
diberhentikan : henti
diberlakukan : laku
diberondong : berondong
dibiarkan : biar
dibiasakan : biasa
dibidik : bidik
dibilang : bilang
dibina : bina
dibuka : buka
dibuntuti : buntut
dibutuhkan : butuh
dicabut : cabut
dicantumkan : cantum
dicapai : capai
dicatatkan : catat
dicek : cek
dicicil : cicil
dicocokkan : cocok
dicopot : copot
didalami : dalam
didampingi : damping
didanai : dana
didasarkan : dasar
didata : data
didatangi : datang
didekati : dekat
dideritanya : derita
didiskualifikasi : diskualifikasi
didiskusikan : diskusi
didoakan : doa
didominasi : dominasi
didorong : dorong
diduduki : duduk
diduga : duga
didukung : dukung
diegos : egos
dieksplorasi : eksplorasi
diekspor : ekspor
diembuskan : embus
dievakuasi : evakuasi
dievaluasi : evaluasi
difokuskan : fokus
diformula : formula
digabungkan : gabung
digabungnya : gabung
diganggu : ganggu
digantikan : ganti
digarap : garap
digelar : gelar
digencet : gencet
dihadapi : hadap
dihadapinya : hadap
dihadiri : hadir
dihadirkan : hadir
dihampiri : hampir
dihantam : hantam
dihapus : hapus
diharapkan : harap
diharuskan : harus
dihasilkan : hasil
dihelat : helat
dihidupkan : hidup
dihilangkan : hilang
dihitung : hitung
dihormati : hormat
diikuti : ikut
diimbangi : imbang
diinisiasi : inisiasi
diinventarisasi : inventarisasi
diisi : isi
dijadwalkan : jadwal
dijalani : jalan
dijalaninya : jalan
dijalankan : jalan
dijamin : jamin
dijual : jual
dijuluki : juluk
dikaitkan : kait
dikali : kali
dikasi : kasi
dikasih : kasih
dikawal : kawal
dikecualikan : kecuali
dikelola : kelola
dikembalikan : kembali
dikembangkan : kembang
dikenai : kena
dikenakan : kena
dikenal : kenal
dikendalikan : kendali
dikendalikannya : kendali
dikerahkan : kerah
dikhawatirkan : khawatir
dikirim : kirim
diklasemen : klasemen
dikonfirmasi : konfirmasi
dikuasai : asai
dikukuhkan : kukuh
dikumpulkan : kumpul
dikunjungi : kunjung
dikuntit : kuntit
dikurangi : rang
dikutip : kutip
dilakoni : lakon
dilaksanakan : laksana
dilakukannya : laku
dilanjut : lanjut
dilanjutkan : lanjut
dilansir : lansir
dilantik : lantik
dilantiknya : lantik
dilaporkan : lapor
dilatih : latih
dilawan : lawan
dilayani : layan
dilelang : lelang
dilengkapi : lengkap
dilepas : lepas
dilibatkan : libat
dilimpahkan : limpah
dilirik : lirik
dilontarkan : lontar
diluncurkan : luncur
dilupakan : lupa
dimainkan : main
dimaknai : makna
dimaksimalkan : maksimal
dimana : mana
dimanfaatkan : manfaat
dimas : mas
dimasukkan : masuk
dimatikan : mati
dimenangkan : menang
dimens : mens
dimeriahkan : riah
dimiliki : milik
dimilikinya : milik
dimintakan : minta
dimohon : mohon
dinaikkan : naik
dinikmati : nikmat
dinilai : nilai
dinyatakan : nyata
dioperasikan : operasi
dipadukan : padu
dipakai : pakai
dipandang : pandang
dipanggil : panggil
dipangkasnya : pangkas
dipasarkan : pasar
dipasok : pasok
dipecat : pecat
dipekan : pek
dipengaruhi : pengaruh
dipenuhi : penuh
diperbaiki : baik
diperbesar : besar
diperbolehkan : boleh
dipercaya : percaya
dipercepat : cepat
diperdagangkan : dagang
diperebutkan : rebut
diperhatikan : perhati
diperiksa : periksa
diperintah : perintah
diperjuangkan : juang
diperkuat : kuat
diperluas : luas
diperoleh : oleh
diperpanjang : panjang
diperparah : parah
dipersembahkan : sembah
dipersiapkan : siap
dipersyaratkan : syarat
dipertahankan : tahan
dipertandingkan : tanding
dipertemukan : temu
dipertentangkan : tentang
diperuntukkan : untuk
dipetakan : peta
dipikirkan : pikir
dipikul : pikul
dipilih : pilih
dipimpin : pimpin
diprediksi : prediksi
diproduksi : produksi
dipromosikan : promosi
diproses : proses
diproyeksikan : proyeksi
dipungut : pungut
diputuskan : putus
diraih : raih
diramaikan : ramai
diramal : ramal
dirancang : rancang
dirapatkan : rapat
dirasakan : rasa
direalisasi : realisasi
direalisasikan : realisasi
direbut : rebut
direbutnya : rebut
direncanakan : rencana
diresmikan : resmi
direstrukturisasi : restrukturisasi
dirilis : rilis
dirok : rok
dirombak : rombak
dirotasi : rotasi
disahkan : sah
disaksikan : saksi
disalip : salip
disalurkan : salur
disambungkan : sambung
disambut : sambut
disampaikannya : sampai
disapa : sapa
disapu : sapu
disebabkan : sebab
disebutnya : sebut
diselamatkan : selamat
diselenggarakan : selenggara
diselesaikan : selesai
diselundupkan : selundup
disepakati : pakat
diserahkan : serah
diserang : serang
diserap : serap
diservisnya : servis
disesuaikan : sesuai
disetorkan : setor
disiapkan : siap
disiarkan : siar
disidangkan : sidang
disinggung : singgung
diskusikan : diskusi
disorot : sorot
disumbangkan : sumbang
disusul : susul
disusun : susun
disyaratkan : syarat
ditahan : tahan
ditambah : tambah
ditampilkan : tampil
ditandai : tanda
ditangani : tangan
ditanggung : tanggung
ditangkap : tangkap
ditargetkan : target
ditarik : tarik
ditawarkan : tawar
ditekan : tekan
ditempati : tempat
ditempatkan : tempat
ditemui : temu
ditemukan : temu
ditentukan : tentu
diterapkan : terap
diterbitkan : terbit
diterbitkannya : terbit
diterima : terima
diterjang : terjang
diterjemahkan : terjemah
diteruskan : terus
ditetapkan : tetap
ditimbulkan : timbul
ditinggalkan : tinggal
ditingkatkan : tingkat
ditopang : topang
ditugaskan : tugas
ditulis : tulis
ditumpangi : tumpang
ditunda : tunda
dituntaskan : tuntas
diturunkan : turun
ditutup : tutup
diubah : ubah
diuji : uji
diukur : ukur
diulangi : ulang
diumumkan : umum
diundang : undang
diundangkan : undang
diunggulkan : unggul
diuntungkan : untung
diurus : urus
diusulkan : usul
diwujudkan : wujud
diyakini : yakin
doakan : doa
dorongan : dorong
duetnya : duet
dugaan : duga
dukungan : dukung
dwidilanmchtr_ : dwidilanmchtr
eceran : ecer
edaran : edar
efeknya : efek
ekonominya : ekonomi
ekosistemnya : ekosistem
eksis : eks
emasnya : emas
emosinya : emosi
fadillah : fadil
fasilitasi : fasilitas
finalisasi : final
fokuskan : fokus
fokusnya : fokus
fotonya : foto
gabungan : gabung
gagalkan : gagal
gambaran : gambar
gangguan : ganggu
gantian : ganti
gantikan : ganti
gelaran : gelar
gerainya : gerai
gerakan : gera
gesekan : gesek
getaran : getar
gini : gin
groginya : grogi
gugatan : gugat
guncangan : guncang
hadapan : hadap
hadapi : hadap
hadi : had
hajatan : hajat
halnya : hal
hambatan : hambat
harapan : harap
harapannya : harap
harapkan : harap
hargai : harga
harganya : harga
harian : hari
harinya : hari
hasilkan : hasil
hasilnya : hasil
hawanya : hawa
hiburan : hibur
hidupku : hidup
hidupnya : hidup
hilirisasi : hilir
himpunan : himpun
hindari : hindar
hitungan : hitung
hitungannya : hitung
hubungan : hubung
hubungannya : hubung
hukuman : hukum
hulunya : hulu
hunian : huni
idealnya : ideal
identitasnya : identitas
ikatan : ikat
ikutan : ikut
ikuti : ikut
imbuhnya : imbuh
impian : impi
impiannya : impi
implementasinya : implementasi
indahnya : indah
individunya : individu
induknya : induk
industrinya : industri
inspirasinya : inspirasi
intinya : inti
investasinya : investasi
itunya : itu
itupun : itu
iuran : iur
izinkan : izin
jabatan : jabat
jabatannya : jabat
jajaran : jajar
jajarannya : jajar
jalani : jalan
jalannya : jalan
jalurnya : jalur
jaminan : jamin
jangkauan : jangkau
jaringan : jaring
jatuhnya : jatuh
jawabannya : jawab
jebolan : jebol
jemputan : jemput
juaranya : juara
kaitannya : kait
kajian : kaji
kakaknya : kakak
kakinya : kaki
kalahnya : kalah
kalinya : kali
kandungan : kandung
kandungannya : kandung
kansnya : kans
kantah : kan
kantoran : kantor
kantornya : kantor
kapasitasnya : kapasitas
karakternya : karakter
karibnya : karib
kariernya : karier
keakraban : akrab
keamanan : aman
keandalan : andal
keanu : anu
kebabak : babak
kebahagiaan : bahagia
kebakaran : bakar
kebanggaan : bangga
kebangkitan : bangkit
kebangsaan : bangsa
keberadaan : ada
keberangkatan : berangkat
keberangkatannya : berangkat
keberanian : berani
keberatan : berat
keberhasilan : hasil
keberlanjutan : lanjut
kebersamaan : sama
kebersihan : bersih
kebiasaan : biasa
kebiasaannya : biasa
kebijakan : bijak
kebisingan : bising
kebosanan : bosan
kebugaran : bugar
kebutuhan : butuh
kebutuhannya : butuh
kecelakaan : celaka
kecenderungan : cenderung
kecenderungannya : cenderung
kecepatan : cepat
kecepatannya : cepat
kecipratan : ciprat
kecurangan : curang
kedapatan : dapat
kedekatan : dekat
kedelapan : delap
kedinasan : dinas
kedisiplinan : disiplin
kedudukan : duduk
keekonomian : ekonomi
keekonomiannya : ekonomi
keempat : empat
keenam : enam
keenamnya : enam
kegagalan : gagal
kegiatan : giat
kegiatannya : giat
kegigihan : gigih
kehabisan : habis
kehadiran : hadir
kehadirannya : hadir
kehidupan : hidup
kehilangan : hilang
kehormatan : hormat
keikut : ikut
kejadian : jadi
kejagung : jagung
kejaksaan : jaksa
kejaran : kejar
kejelasan : jelas
kejenuhan : jenuh
kejuaraan : juara
kejutan : kejut
kekalahan : kalah
kekompakan : kompak
kekuatan : kuat
kekuatanku : kuat
kekurangan : kurang
kelahiran : lahir
kelalaian : lalai
kelancaran : lancar
kelangkaan : langka
kelangsungan : langsung
kelanjutan : lanjut
kelaparan : lapar
kelasnya : kelas
kelayakan : layak
kelebihan : lebih
kelimanya : lima
kelincahan : lincah
kelistrikan : listrik
kelolaan : kelola
kelolosan : lolos
keluaran : keluar
keluarkan : keluar
kelulusan : kelulus
kemajuan : maju
kemakmuran : makmur
kemampuan : mampu
kemampuannya : mampu
kemandirian : mandiri
kemasan : kemas
kemauan : mau
kembalinya : kembali
kembangkan : kembang
kemenangan : menang
kementan : tan
kementerian : menteri
kemeriahan : riah
kemiskinan : miskin
kemitraan : mitra
kemoto : moto
kemudahan : mudah
kemurnian : murni
kenaikan : naik
kenavigasian : navigasi
kendalanya : kendala
kendalikan : kendali
kendaraan : kendara
kenegaraan : negara
kenyamanan : nyaman
kepabeanan : pabean
kepadaku : kepada
kepadatan : padat
keparahan : parah
kepastian : pasti
kepatuhan : patuh
kepegawaian : pegawai
kepekaan : peka
kepemilikan : milik
kepemimpinan : pimpin
kepemudaan : pemuda
kepengurusan : urus
kepentingan : penting
kepercayaan : percaya
kepergok : pergok
kepolisian : polisi
kepresidenan : presiden
keputusan : putus
keputusannya : putus
keramaian : ramai
kerasnya : keras
kerentanan : rentan
kericuhan : ricuh
keriuhan : riuh
kerugian : rugi
kerusakan : rusa
kesalahan : salah
kesatuan : satu
kesebelas : sebelas
keseharian : hari
kesehatan : sehat
keseimbangan : imbang
kesejahteraan : sejahtera
keselamatan : selamat
kesembilan : sembilan
kesempatan : sempat
kesenjangan : senjang
kesepahaman : paham
kesepakatan : sepakat
kesepuluh : puluh
keseruan : seru
kesesuaian : sesuai
kesesuaiannya : sesuai
kesiapan : kesiap
kesiapannya : kesiap
kesinambungan : sinambung
kesulitan : sulit
kesyahbandaran : syahbandar
ketahanan : tahan
ketahui : tahu
ketegangan : tegang
ketegasan : tegas
ketenangan : tenang
ketentuan : tentu
ketepatan : tepat
keterangan : terang
keterangannya : terang
keterbatasan : batas
keterbukaan : buka
ketergantungan : gantung
keterhubungan : hubung
keterikatan : ikat
keterjangkauan : jangkau
keterkaitan : kait
keterlambatan : lambat
keterlibatan : libat
ketersediaan : sedia
ketertiban : tertib
ketertinggalan : tinggal
ketetapan : tetap
ketiga : tiga
ketiganya : tiga
ketimpangan : timpang
ketinggalan : tinggal
ketujuh : tujuh
keuangan : uang
keuangannya : uang
keunggulan : unggul
keunggulannya : unggul
keuntungan : untung
keuntunganku : untung
kewajiban : wajib
kewaspadaan : waspada
kewenangan : wenang
kewilayahan : wilayah
keyakinan : yakin
kimi : kim
kinerja : kerja
kiprahnya : kiprah
kisaran : kisar
kitanya : kita
kliennya : klien
komitmennya : komitmen
kompatriotnya : kompatriot
komunikasikan : komunikasi
komunikasinya : komunikasi
kondisinya : kondisi
konsepnya : konsep
konsistensinya : konsistensi
konsumennya : konsumen
koperâ : koper
kotoran : kotor
kotorannya : kotor
kualitasnya : kualitas
kuasai : kuasa
kuatnya : kuat
kukatakan : kata
kumara : mara
kumite : mite
kumpulkan : kumpul
kunjungan : kunjung
kupikir : pikir
kurangnya : kurang
kurasa : rasa
kurasikan : rasi
kursinya : kursi
kuungkapkan : ungkap
labelnya : label
ladeni : laden
lahannya : lahan
lahirnya : lahir
lakukan : laku
lalui : lalu
landasan : landas
langganan : langgan
langkahnya : langkah
lanjutan : lanjut
lanjuti : lanjut
lanjutkan : lanjut
lantaran : lantar
lapangan : lapang
laporan : lapor
larangan : larang
latihan : latih
latihannya : latih
lawannya : lawan
layanan : layan
lemparannya : lempar
lengkapi : lengkap
lengkapnya : lengkap
levelnya : level
lewati : lewat
lewatkan : lewat
libatkan : libat
liburan : libur
liburanmu : libur
lingkungan : lingkung
lingkungannya : lingkung
lintasan : lintas
longsoran : longsor
lonjakan : lonjak
lowongan : lowong
mainnya : main
majukan : maju
makanan : makan
maksimalkan : maksimal
maksudnya : maksud
maluku : malu
manapun : mana
manfaatkan : manfaat
manfaatnya : manfaat
manggari : manggar
mapi : map
masukan : masuk
masuki : masuk
masuknya : masuk
materinya : materi
mauludi : maulud
maunya : mau
medianya : media
mekanismenya : mekanisme
melacak : lacak
melahap : lahap
melahirkan : lahir
melaju : laju
melajukan : laju
melakoni : lakon
melaksanakan : laksana
melakukannya : laku
melambungkan : lambung
melampaui : lampau
melamun : lamun
melancarkan : lancar
melanda : landa
melanggar : langgar
melangkah : lang
melanjutkan : lanjut
melansir : lansir
melantik : lantik
melaporkan : lapor
melaporkannya : lapor
melarang : larang
melawan : lawan
melayani : layan
melebarkan : lebar
melebihi : lebih
meledek : ledek
melekat : lekat
melemah : lemah
melemahnya : lemah
melengkapi : lengkap
melepas : lepas
melepaskan : lepas
melesat : lesat
meletakkan : letak
melewati : lewat
melewatkan : lewat
melibatkan : libat
melindungi : lindung
melintas : lintas
melintasi : lintas
meliputi : liput
meloloskan : lolos
melompati : lompat
melonjak : lonjak
melorot : lorot
meluncur : luncur
meluncurkan : luncur
memacu : pacu

,stopwords_removed_isi,stemmed_isi
0,"[ketua, umumkomite, olahraga, nasional, indone...","[ketua, umumkomite, olahraga, nasional, indone..."
1,"[pengurus, pusat, kickboxing, indonesia, pp, k...","[urus, pusat, kickboxing, indonesia, pp, kbipe..."
2,"[lina, hisage, atlet, tolak, peluru, wamena, p...","[lina, hisage, atlet, tolak, peluru, wamena, p..."
3,"[timnas, equestrian, indonesiasudah, bertolak,...","[timnas, equestrian, indonesiasudah, tolak, je..."
4,"[ciamis, siswa, sd, mengikuti, lomba, olahraga...","[ciamis, siswa, sd, ikut, lomba, olahraga, tra..."

In [11]:
from collections import Counter

# Gabungkan semua token yang bertangkai menjadi satu daftar
all_stemmed_words = [word for tokens in df['stemmed_isi'] for word in tokens]

# Hitung frekuensi setiap kata
word_frequencies = Counter(all_stemmed_words)

# Menampilkan kata-kata yang paling umum dan frekuensinya
print("Top Most Frequent Words:")
for word, frequency in word_frequencies.most_common():
    print(f"{word}: {frequency}")

Top Most Frequent Words:
indonesia: 354
jakarta: 268
menteri: 194
to: 189
scroll: 187
with: 187
content: 187
rp: 187
continue: 186
balap: 165
uang: 164
jalan: 158
emas: 144
hasil: 143
poin: 140
posisi: 138
atlet: 136
kembang: 132
juara: 132
kuat: 129
dukung: 126
latih: 126
marquez: 126
usaha: 121
proses: 117
motogp: 117
tingkat: 116
jabat: 114
sesuai: 111
games: 109
butuh: 108
purbaya: 107
nilai: 106
milik: 105
suahasil: 103
nasional: 101
tim: 101
perintah: 100
main: 99
kerja: 98
harga: 98
detik: 94
selesai: 92
prabowo: 91
negara: 90
marc: 90
september: 88
salah: 86
asi: 86
bangun: 85
capai: 84
tumbuh: 84
ekonomi: 81
lanjut: 79
rabu: 79
menang: 79
temu: 79
catat: 77
bezzecchi: 77
layan: 77
dasar: 77
harap: 76
presiden: 76
lrt: 76
tanding: 75
martin: 75
ya: 75
medali: 73
kondisi: 73
putra: 73
kait: 72
kali: 72
orang: 71
san: 71
stasiun: 71
pb: 69
utama: 69
serta: 68
raih: 68
terima: 68
penuh: 67
marino: 67
olahraga: 66
bawa: 66
terang: 65
industri: 65
triliun: 65
pimpin: 64
tiga: 64
masuk: 63
kelola: 63
video: 63
masyarakat: 62
putri: 62
dunia: 62
jepang: 62
turun: 62
tambah: 62
daerah: 62
motor: 62
buka: 61
pusat: 60
nomor: 60
siap: 59
pramono: 59
investasi: 59
pt: 59
cepat: 58
rencana: 57
jaga: 57
tahan: 57
lap: 57
selasa: 57
selatan: 57
laku: 57
tentu: 57
kapal: 56
bisnis: 56
gambasvideo: 55
tutup: 54
target: 54
langsung: 54
hadir: 54
proyek: 54
dki: 54
ganda: 53
alam: 52
ikut: 52
mampu: 52
sektor: 52
energi: 52
persero: 52
langgan: 52
prestasi: 51
sempat: 51
ajar: 51
potensi: 51
kota: 51
direktur: 51
bijak: 51
resmi: 49
langkah: 49
hadap: 49
juta: 49
miliar: 49
gelar: 48
ubah: 48
kepala: 48
atur: 48
naik: 48
alami: 47
tampil: 47
angka: 47
baik: 46
saing: 46
putus: 46
bantu: 45
rider: 45
pasar: 45
saham: 45
wib: 44
marco: 44
seri: 44
unggul: 44
ombak: 44
program: 43
manfaat: 43
tahap: 43
lihat: 43
wakil: 43
daya: 43
produksi: 43
bonus: 43
djarum: 43
beras: 43
sedia: 42
ekosistem: 42
ajang: 42
jorge: 42
lengkap: 41
percaya: 41
sebut: 41
kelas: 41
musim: 41
barat: 40
tulis: 40
produk: 40
moto: 40
kawasan: 40
dagang: 40
rumah: 39
koordinasi: 39
misano: 39
fokus: 39
total: 39
bbm: 39
apresiasi: 38
minggu: 38
selenggara: 38
simak: 38
group: 38
fortifikasi: 38
konsumen: 38
juang: 37
bagus: 37
oktober: 37
pertamina: 37
upaya: 37
manggarai: 37
internasional: 36
usia: 36
negeri: 36
bea: 36
tinggal: 36
nggak: 36
chandra: 36
level: 35
aktivitas: 35
aman: 35
beda: 35
besar: 35
hitung: 35
fiskal: 35
asri: 35
giat: 34
hubung: 34
dorong: 34
arah: 34
jaring: 34
cari: 34
peluang: 34
ruang: 34
tikung: 34
gagal: 34
world: 34
cukai: 34
alex: 34
duga: 34
pajak: 34
transaksi: 34
bina: 33
beli: 33
ambil: 33
klasemen: 33
finis: 33
tangan: 33
lawan: 33
danantara: 33
kelapa: 33
hidup: 32
serah: 32
lantik: 32
ganti: 32
jalur: 32
aku: 32
sesi: 32
muda: 32
batas: 32
kantor: 32
rapat: 32
menkeu: 32
operasional: 32
tni: 31
pasang: 31
race: 31
tekan: 31
andal: 31
pasok: 31
data: 31
jenderal: 31
buruh: 31
luas: 30
tujuh: 30
lapang: 30
kalah: 30
jual: 30
informasi: 30
dana: 30
ketua: 29
pilih: 29
kompetisi: 29
laga: 29
tantang: 29
empat: 29
sumber: 29
wajib: 29
komunitas: 29
kualitas: 29
bimo: 29
integrasi: 28
fasilitas: 28
perhati: 28
nyata: 28
kualifikasi: 28
transportasi: 28
periksa: 28
menit: 28
kolaborasi: 28
utang: 28
bentuk: 27
periode: 27
oleh: 27
ducati: 27
crash: 27
regu: 27
media: 27
lintas: 27
jadwal: 27
global: 27
sistem: 27
hukum: 27
kemenkeu: 27
urus: 26
gabung: 26
dapat: 26
alih: 26
tinggi: 26
podium: 26
rebut: 26
hak: 26
nama: 26
riders: 26
operasi: 26
rugi: 26
subianto: 26
bahlil: 26
tarik: 25
pungkas: 25
aichinagoya: 25
bulutangkis: 25
pasti: 25
senang: 25
badan: 25
acosta: 25
basket: 25
ri: 25
sirkuit: 25
barang: 25
henti: 25
tindak: 25
set: 25
us: 25
m: 25
komitmen: 25
tbk: 25
anggar: 25
nazara: 25
bumn: 25
evaluasi: 24
anak: 24
maksimal: 24
pekan: 24
risiko: 24
modal: 24
senior: 24
aksi: 24
tiket: 24
tuju: 24
enam: 24
utara: 24
kendara: 24
biaya: 24
tetap: 24
strategis: 24
lindung: 24
dampak: 24
hilang: 24
bayar: 24
gram: 24
tunda: 23
turut: 23
masingmasing: 23
sukses: 23
standar: 23
jumat: 23
tanah: 23
adhi: 23
sisi: 23
sisa: 23
veda: 23
wilayah: 23
minimum: 23
yudhi: 23
sadewa: 23
akses: 23
minyak: 23
lng: 23
uln: 23
merah: 22
cabang: 22
kasih: 22
guna: 22
kamis: 22
turnamen: 22
campur: 22
olimpiade: 22
keras: 22
timur: 22
kapasitas: 22
listrik: 22
jangka: 22
u: 22
pen: 22
kg: 22
uji: 22
audisi: 22
salip: 22
aldeguer: 22
bank: 22
gading: 22
mrt: 22
infrastruktur: 22
labuh: 22
antam: 22
isi: 21
selamat: 21
momentum: 21
bahan: 21
depan: 21
tua: 21
serikat: 21
ukur: 21
nathan: 21
pasuk: 21
kendali: 21
banding: 21
rangkai: 21
ketat: 21
strategi: 21
korea: 21
rasa: 21
berat: 21
akibat: 21
angkat: 21
bold: 21
terap: 21
laksana: 21
as: 21
lapor: 21
rok: 21
usul: 21
said: 21
panjang: 21
kereta: 21
awas: 21
jasa: 21
mnk: 21
investor: 21
lina: 20
tahun: 20
disiplin: 20
jatuh: 20
puncak: 20
the: 20
open: 20
pikir: 20
acara: 20
agustus: 20
paham: 20
mitra: 20
ratarata: 20
bahas: 20
inflasi: 20
dpr: 20
tuan: 19
kutip: 19
tugas: 19
dekat: 19
lepas: 19
karakter: 19
cakup: 19
malam: 19
kemarin: 19
berangkat: 19
grand: 19
papar: 19
kilogram: 19
unit: 19
proyeksi: 19
pedro: 19
anggota: 19
a: 19
satu: 19
persen: 19
giannantonio: 19
kuarter: 19
pensiun: 19
bunga: 19
whoosh: 19
batal: 19
bambang: 19
kurang: 18
profesional: 18
putih: 18
tolak: 18
kumpul: 18
duduk: 18
motivasi: 18
khusus: 18
timnas: 18
lingkung: 18
bersih: 18
insiden: 18
peringkat: 18
publik: 18
sambung: 18
umum: 18
komunikasi: 18
gresini: 18
provinsi: 18
tempat: 18
untung: 18
gerak: 18
aprilia: 18
tenis: 18
mata: 18
kabupaten: 18
susul: 18
timbang: 18
indeks: 18
upah: 18
apbn: 18
ops: 18
ton: 18
bp: 18
dony: 18
international: 17
bangkit: 17
seleksi: 17
jam: 17
atas: 17
beban: 17
bagi: 17
lomba: 17
start: 17
sabtu: 17
kejar: 17
awal: 17
bicara: 17
final: 17
lembaga: 17
kenal: 17
bakat: 17
alexander: 17
super: 17
ega: 17
pratama: 17
partai: 17
throttle: 17
izin: 17
korban: 17
kpk: 17
ojk: 17
positif: 16
sekolah: 16
alas: 16
senin: 16
sehat: 16
pbsi: 16
pelatnas: 16
bukti: 16
gas: 16
kategori: 16
mobil: 16
momen: 16
coba: 16
p: 16
perak: 16
daftar: 16
saudi: 16
ribu: 16
esports: 16
jarak: 16
inka: 16
mudah: 16
digit: 16
renang: 16
velodrome: 16
i: 16
teknologi: 16
bursa: 16
organisasi: 15
pers: 15
fisik: 15
jawa: 15
semangat: 15
gp: 15
fadia: 15
ulang: 15
ganggu: 15
sinergi: 15
desember: 15
kesiap: 15
air: 15
china: 15
arab: 15
x: 15
mental: 15
solusi: 15
panglima: 15
tata: 15
bakar: 15
kudus: 15
bogor: 15
champion: 15
mineral: 15
simoncelli: 15
optimal: 15
land: 15
modern: 15
minta: 15
belanja: 15
regional: 15
amran: 15
kirim: 14
gedung: 14
cipta: 14
performa: 14
susun: 14
teknis: 14
situasi: 14
tunggal: 14
piala: 14
lancar: 14
kena: 14
asia: 14
benarbenar: 14
rancang: 14
makan: 14
agius: 14
ktm: 14
wujud: 14
yamaha: 14
honda: 14
fabio: 14
tanggal: 14
perunggu: 14
dpd: 14
eko: 14
pengaruh: 14
maju: 14
ceo: 14
pabean: 14
team: 14
carnet: 14
terbit: 14
contoh: 14
pakai: 14
rilis: 14
racing: 14
mandiri: 14
nasib: 14
celaka: 14
pantau: 14
dolar: 14
juli: 14
istana: 14
salur: 14
migas: 14
online: 14
jis: 14
beber: 14
lahan: 14
kompleks: 14
sidang: 14
summarecon: 14
atrbpn: 14
rute: 14
metro: 14
koni: 13
iring: 13
multievent: 13
pegang: 13
panas: 13
aspek: 13
baca: 13
muncul: 13
ubed: 13
sosial: 13
amri: 13
simpan: 13
sih: 13
hadiah: 13
tech: 13
mesin: 13
lahir: 13
david: 13
bagnaia: 13
libat: 13
sayang: 13
alti: 13
talenta: 13
tunggu: 13
axcr: 13
tanjung: 13
lolos: 13
cermin: 13
keluar: 13
digital: 13
karya: 13
kelompok: 13
ku: 13
rantai: 13
bilang: 13
merek: 13
langgar: 13
efektif: 13
hapus: 13
tumpang: 13
subsidi: 13
gubernur: 13
rendah: 13
dalam: 13
internal: 13
pegawai: 13
ihsg: 13
lemah: 13
realisasi: 13
pu: 13
mandalika: 12
marciano: 12
bola: 12
pp: 12
platform: 12
kontribusi: 12
tonton: 12
bandara: 12
bareng: 12
maaf: 12
matang: 12
mekanisme: 12
pulang: 12
ban: 12
regulasi: 12
tepat: 12
practice: 12
sulit: 12
jenis: 12
jamin: 12
syarat: 12
priok: 12
kembali: 12
selisih: 12
buruk: 12
game: 12
minimal: 12
sebab: 12
label: 12
serang: 12
tennis: 12
circuit: 12
s: 12
almansa: 12
abraham: 12
nikmat: 12
panah: 12
pentathlon: 12
ump: 12
jajal: 12
indikasi: 12
praktik: 12
isu: 12
domestik: 12
distribusi: 12
commuter: 12
tambang: 12
dmo: 12
hormat: 11
amerika: 11
gaya: 11
nagoya: 11
thailand: 11
sorot: 11
dejan: 11
amrinita: 11
cipayung: 11
pola: 11
baru: 11
luca: 11
marini: 11
karier: 11
tang: 11
pole: 11
fp: 11
anakanak: 11
alias: 11
fermin: 11
kenneth: 11
bekas: 11
cup: 11
gadai: 11
ata: 11
aju: 11
identitas: 11
fase: 11
panitia: 11
prediksi: 11
cegah: 11
lewat: 11
karan: 11
fernandez: 11
nyaman: 11
quiles: 11
uriarte: 11
imbang: 11
pasal: 11
malu: 11
imam: 11
suku: 11
stabilitas: 11
tuntut: 11
ditjen: 11
management: 11
djp: 11
dividen: 11
smra: 11
aset: 11
kapabilitas: 11
gadingmanggarai: 11
edar: 11
pidana: 11
bas: 11
muat: 11
batu: 11
bara: 11
sampah: 11
semester: 11
freeport: 11
portofolio: 11
ptba: 11
asuransi: 11
icomex: 11
libur: 11
asal: 10
kbi: 10
atletatlet: 10
sumbang: 10
signifikan: 10
januari: 10
pecah: 10
rekor: 10
pertama: 10
personal: 10
tanggung: 10
pagi: 10
status: 10
murni: 10
peran: 10
pindah: 10
koleksi: 10
gitu: 10
director: 10
jabodetabek: 10
bandung: 10
lapar: 10
grid: 10
kompetitif: 10
beri: 10
delapan: 10
country: 10
logistik: 10
prosedur: 10
event: 10
skor: 10
muhammad: 10
herindra: 10
bangsa: 10
suara: 10
pulih: 10
danish: 10
bal: 10
chang: 10
duel: 10
bikin: 10
puas: 10
business: 10
hakim: 10
klaim: 10
babak: 10
ramai: 10
q: 10
lokasi: 10
erwin: 10
esdm: 10
antre: 10
spbu: 10
udah: 10
kspi: 10
konferensi: 10
direktorat: 10
warga: 10
virgo: 10
transport: 10
timbul: 10
hgb: 10
manajemen: 10
komoditas: 10
transformasi: 10
fitch: 10
pos: 10
pelindo: 10
tega: 10
kandung: 10
gizi: 10
bei: 10
rkab: 10
km: 10
pokok: 10
tembaga: 10
insurance: 10
sport: 9
timor: 9
senayan: 9
puluh: 9
sea: 9
lempar: 9
materi: 9
keluarga: 9
teknik: 9
adaptasi: 9
damping: 9
ujung: 9
debut: 9
australia: 9
masalah: 9
sambut: 9
red: 9
sejarah: 9
administrasi: 9
saksi: 9
pria: 9
prasetyo: 9
bidang: 9
e: 9
sepenuh: 9
rally: 9
dokumen: 9
kontainer: 9
club: 9
putar: 9
tenaga: 9
singleton: 9
saputera: 9
grup: 9
tunjuk: 9
generasi: 9
fondasi: 9
mantan: 9
area: 9
foundation: 9
championship: 9
india: 9
morbidelli: 9
spa: 9
tahu: 9
tawar: 9
relatif: 9
jarang: 9
agus: 9
aji: 9
robby: 9
unjuk: 9
golf: 9
halim: 9
joaquin: 9
fed: 9
dirjen: 9
anung: 9
dukuh: 9
namanama: 9
talent: 9
nusantara: 9
komisi: 9
petrokimia: 9
likuiditas: 9
hulu: 9
line: 9
trainset: 9
krl: 9
kai: 9
pecat: 9
prerogatif: 9
beliau: 9
varnion: 9
kanal: 9
tony: 9
pound: 9
qodari: 9
ilegal: 9
leste: 8
sarana: 8
indah: 8
buat: 8
benah: 8
kiprah: 8
habis: 8
hari: 8
coach: 8
equestrian: 8
jerman: 8
sprint: 8
prix: 8
anggap: 8
rakyat: 8
hyrox: 8
cabut: 8
mix: 8
komposisi: 8
bagas: 8
nova: 8
jiwa: 8
banget: 8
lari: 8
alfamart: 8
aplikasi: 8
skala: 8
nila: 8
biasa: 8
moga: 8
maksud: 8
bull: 8
arena: 8
sama: 8
kejut: 8
ajak: 8
bangga: 8
perdana: 8
ada: 8
ii: 8
kunci: 8
agenda: 8
motorsport: 8
gravel: 8
cocok: 8
lambat: 8
iwf: 8
seru: 8
series: 8
jadi: 8
kaya: 8
yudha: 8
deny: 8
pool: 8
of: 8
esi: 8
lokal: 8
italia: 8
geser: 8
hambat: 8
bahagia: 8
gembira: 8
karantina: 8
non: 8
garuda: 8
v: 8
tempo: 8
sanksi: 8
celah: 8
maximo: 8
koper: 8
semifinal: 8
gera: 8
speed: 8
gokart: 8
perspektif: 8
luncur: 8
market: 8
makassar: 8
faktor: 8
iya: 8
sinyal: 8
konsumsi: 8
pangan: 8
gali: 8
koalisi: 8
skema: 8
obligasi: 8
boulevard: 8
eselon: 8
djaka: 8
birokrasi: 8
blok: 8
tan: 8
ekspansi: 8
buang: 8
satgas: 8
tipu: 8
zona: 8
dinamika: 8
parlemen: 8
kabinet: 8
sertijab: 8
shinta: 8
kredibilitas: 8
nasabah: 8
tugu: 8
sarjito: 8
sertifikasi: 8
selundup: 8
pon: 7
wadah: 7
papua: 7
sore: 7
rotasi: 7
sosok: 7
pada: 7
syukur: 7
inti: 7
tanda: 7
alwi: 7
yusuf: 7
tokyo: 7
gulir: 7
city: 7
viral: 7
lansir: 7
sakit: 7
double: 7
dkk: 7
apri: 7
antusiasme: 7
tembus: 7
raya: 7
ryan: 7
yogyakarta: 7
garis: 7
konsep: 7
pemuda: 7
era: 7
satusatunya: 7
janji: 7
sepakbola: 7
francesco: 7
porprov: 7
wali: 7
iin: 7
cetak: 7
sepak: 7
konsisten: 7
asisten: 7
mudahmudahan: 7
bima: 7
had: 7
temanteman: 7
sumatera: 7
rangka: 7
popprov: 7
formula: 7
servis: 7
tertib: 7
duo: 7
besi: 7
klub: 7
timpal: 7
takluk: 7
sasar: 7
taufik: 7
mite: 7
kemenpora: 7
tangki: 7
pebulutangkis: 7
kemas: 7
judi: 7
rins: 7
laps: 7
pribadi: 7
live: 7
makna: 7
sipil: 7
pintu: 7
pihakpihak: 7
livery: 7
climbing: 7
konsistensi: 7
tembak: 7
biar: 7
kultur: 7
gue: 7
chapter: 7
integritas: 7
ungkap: 7
diskusi: 7
ringan: 7
bps: 7
sulawesi: 7
ksppb: 7
ratus: 7
wijayanto: 7
samuel: 7
model: 7
setor: 7
struktur: 7
agung: 7
tangkap: 7
swasta: 7
pacific: 7
relevan: 7
darat: 7
implementasi: 7
profil: 7
otoritas: 7
mutu: 7
dinas: 7
pinjam: 7
bendahara: 7
volume: 7
ab: 7
phr: 7
tara: 7
sucor: 7
am: 7
aph: 7
perban: 7
president: 7
copot: 7
bulan: 7
tht: 7
laba: 7
figur: 7
sri: 7
mulyani: 7
bmks: 7
akrab: 6
alat: 6
amatir: 6
jangkau: 6
terbang: 6
optimistis: 6
jajar: 6
peluru: 6
meter: 6
yeremias: 6
variasi: 6
situ: 6
tangerang: 6
aktif: 6
cuaca: 6
sapu: 6
aragon: 6
bahu: 6
partner: 6
sapa: 6
pesan: 6
aichi: 6
malaysia: 6
diskualifikasi: 6
nikolaus: 6
silva: 6
penting: 6
sepakat: 6
padu: 6
oh: 6
rekan: 6
sabar: 6
promosi: 6
baris: 6
trias: 6
sengit: 6
lantas: 6
belakang: 6
dominasi: 6
kursi: 6
kontingen: 6
tangkis: 6
potensial: 6
sifat: 6
mohon: 6
cantum: 6
asistensi: 6
sembilan: 6
kantong: 6
cedera: 6
iv: 6
ketemu: 6
suasana: 6
tour: 6
jati: 6
singapura: 6
tebak: 6
cinta: 6
riding: 6
imbas: 6
lengser: 6
ben: 6
titik: 6
gor: 6
semarang: 6
baron: 6
mens: 6
nusa: 6
kepadadetiksport: 6
franco: 6
petaka: 6
and: 6
urut: 6
raul: 6
asap: 6
pecco: 6
ita: 6
brian: 6
valentin: 6
perrone: 6
detikcom: 6
lebar: 6
rybakina: 6
tani: 6
singkat: 6
tebing: 6
tukar: 6
sports: 6
dewan: 6
milklife: 6
kalimantan: 6
anthon: 6
langkahlangkah: 6
rolling: 6
wheels: 6
rifqi: 6
eksekutif: 6
kendala: 6
kisar: 6
mayoritas: 6
lahadalia: 6
bpi: 6
dirut: 6
apbd: 6
koneksi: 6
ajaib: 6
assessment: 6
placemaking: 6
inovasi: 6
prinsip: 6
sembari: 6
toko: 6
etanol: 6
baku: 6
fundamental: 6
alokasi: 6
laut: 6
awak: 6
ahy: 6
adrianto: 6
pitojo: 6
perkara: 6
entitas: 6
ahli: 6
sukuk: 6
dermaga: 6
efisien: 6
tari: 6
wenang: 6
jagung: 6
produsen: 6
kompetensi: 6
instansi: 6
awat: 6
jeffrey: 6
oskaria: 6
instrumen: 6
reksa: 6
prioritas: 6
corporate: 6
mobilitas: 6
gaji: 6
byan: 6
tabung: 6
omada: 6
konektivitas: 6
lonjak: 6
cmry: 6
dpum: 6
hki: 6
cicil: 6
pipa: 6
ounces: 6
fleksibilitas: 6
moeharmein: 6
pfi: 6
mega: 6
life: 6
ossy: 6
kustodi: 6
pindar: 6
lubang: 6
didik: 5
erat: 5
ngatino: 5
november: 5
solo: 5
pro: 5
bersamasama: 5
sponsor: 5
center: 5
asean: 5
rutinitas: 5
seharihari: 5
jelang: 5
terminal: 5
bekal: 5
tri: 5
muhamad: 5
zaki: 5
tuntas: 5
untun: 5
training: 5
tenang: 5
cepirit: 5
pergi: 5
bangkok: 5
foto: 5
wietrzyk: 5
alir: 5
joaquinsiti: 5
ramadhanti: 5
doa: 5
sejati: 5
tandem: 5
run: 5
hibur: 5
eksklusif: 5
helat: 5
republik: 5
erick: 5
cc: 5
mentalitas: 5
miller: 5
lakon: 5
austria: 5
quartararo: 5
vr: 5
jakbar: 5
bulu: 5
kent: 5
bencana: 5
asosiasi: 5
aula: 5
induk: 5
cabor: 5
rallycross: 5
modifikasi: 5
ancol: 5
cross: 5
harianto: 5
leader: 5
spare: 5
part: 5
kadin: 5
general: 5
acu: 5
support: 5
dulang: 5
lesat: 5
junior: 5
detiksport: 5
edisi: 5
budi: 5
segar: 5
perempatfinal: 5
by: 5
instagram: 5
konten: 5
pandang: 5
jenjang: 5
asumsi: 5
al: 5
polesitter: 5
lorot: 5
rem: 5
alhasil: 5
manager: 5
tardozzi: 5
ambang: 5
slam: 5
berani: 5
lang: 5
mula: 5
itf: 5
beach: 5
lowside: 5
ai: 5
pramac: 5
starting: 5
row: 5
ngacir: 5
hotel: 5
kuis: 5
street: 5
akun: 5
cermat: 5
asah: 5
isaac: 5
selandia: 5
asing: 5
mario: 5
mangkas: 5
kombinasi: 5
bebas: 5
tahuntahun: 5
challenge: 5
respons: 5
ali: 5
rebound: 5
picks: 5
genre: 5
yuni: 5
sebar: 5
rafalentino: 5
koopsudnas: 5
hut: 5
calon: 5
bus: 5
hujan: 5
panjat: 5
tertawa: 5
banjir: 5
purwoko: 5
kabar: 5
komite: 5
stok: 5
laode: 5
tegak: 5
plus: 5
kilometer: 5
rawamangun: 5
pramuka: 5
matraman: 5
proklamasi: 5
manusia: 5
undang: 5
urban: 5
unsur: 5
multiplier: 5
elektronik: 5
gratis: 5
cek: 5
zulhas: 5
opsi: 5
rapbn: 5
paripurna: 5
korporasi: 5
selat: 5
enggan: 5
ros: 5
kumuh: 5
forum: 5
korupsi: 5
ott: 5
patuh: 5
achmad: 5
diversifikasi: 5
ratings: 5
ijarah: 5
sandar: 5
emisi: 5
produktif: 5
pln: 5
transisi: 5
produktivitas: 5
hemat: 5
polisi: 5
curang: 5
cenderung: 5
perempuan: 5
rti: 5
konvensional: 5
barel: 5
insentif: 5
koridor: 5
triwulan: 5
vice: 5
sekretaris: 5
blakblakan: 5
tarif: 5
angkut: 5
magang: 5
stabil: 5
radio: 5
buy: 5
tp: 5
sl: 5
akhmad: 5
smv: 5
ekspor: 5
reshuffle: 5
ptfi: 5
lebih: 5
masyhud: 5
smelter: 5
raymond: 5
sinambung: 5
accident: 5
mall: 5
timah: 5
bludebit: 5
card: 5
pinjol: 5
djbc: 5
de: 4
gandeng: 4
kickboxing: 4
amanah: 4
kejurnas: 4
pac: 4
liput: 4
jenuh: 4
panggil: 4
asuh: 4
erti: 4
dressage: 4
siswa: 4
pernat: 4
spanyol: 4
dominan: 4
moh: 4
momota: 4
lupa: 4
post: 4
zarif: 4
kotor: 4
tanggap: 4
kaki: 4
furste: 4
syahnawinita: 4
violina: 4
amin: 4
all: 4
tarung: 4
apaapa: 4
gengsi: 4
sengaja: 4
minat: 4
bobot: 4
usung: 4
eropa: 4
felisha: 4
juni: 4
optimisme: 4
bulega: 4
balas: 4
position: 4
seasia: 4
ana: 4
kompak: 4
match: 4
ring: 4
el: 4
pabrikan: 4
latar: 4
kerah: 4
pdi: 4
mutmainnah: 4
takraw: 4
cas: 4
celine: 4
pek: 4
lantar: 4
dadak: 4
paksa: 4
transparan: 4
pendek: 4
buru: 4
fia: 4
rx: 4
jumpa: 4
unjung: 4
kevin: 4
legenda: 4
exchange: 4
list: 4
pasu: 4
feet: 4
delay: 4
adhang: 4
tipe: 4
layak: 4
safety: 4
bayang: 4
gantung: 4
tekad: 4
skuad: 4
badminton: 4
rachel: 4
panggung: 4
jaya: 4
d: 4
lenovo: 4
solid: 4
betulbetul: 4
bakti: 4
antisipasi: 4
karate: 4
wanita: 4
porsi: 4
khawatir: 4
dimotogp: 4
serius: 4
bos: 4
pangkas: 4
kendati: 4
shelton: 4
titel: 4
zverev: 4
praktis: 4
potong: 4
kandang: 4
pms: 4
klaten: 4
redam: 4
intensitas: 4
net: 4
usd: 4
atp: 4
norris: 4
ogura: 4
trackhouse: 4
lcr: 4
zarco: 4
pol: 4
lagilagi: 4
rc: 4
tengah: 4
alvaro: 4
matteo: 4
bertelle: 4
head: 4
eng: 4
hian: 4
joel: 4
adrian: 4
berita: 4
roda: 4
inklusif: 4
national: 4
point: 4
jetski: 4
dito: 4
sertifikat: 4
troy: 4
basis: 4
agresif: 4
leo: 4
siang: 4
toreh: 4
berkat: 4
long: 4
rutin: 4
awards: 4
soccer: 4
festival: 4
tiebreak: 4
tangguh: 4
medium: 4
sentuh: 4
dua: 4
akumulasi: 4
fashion: 4
musik: 4
throttles: 4
orchestra: 4
dekade: 4
selaras: 4
identifikasi: 4
yakin: 4
jones: 4
ingat: 4
kusuma: 4
marsekal: 4
ngurah: 4
dada: 4
peta: 4
kans: 4
asis: 4
jeremy: 4
benar: 4
nonsubsidi: 4
detail: 4
pompa: 4
kirakira: 4
aparat: 4
timbun: 4
modus: 4
kaum: 4
kantorkantor: 4
ruu: 4
ketenagakerjaan: 4
yurisprudensi: 4
bincang: 4
siar: 4
moda: 4
stadium: 4
pulomas: 4
administrator: 4
fungsional: 4
susah: 4
lainlain: 4
landas: 4
hub: 4
effect: 4
revitalisasi: 4
otomatis: 4
rekomendasi: 4
undangundang: 4
aspirasi: 4
hutan: 4
karhutla: 4
kmp: 4
anagata: 4
wacana: 4
aja: 4
mukim: 4
shgb: 4
orangorang: 4
waris: 4
blokir: 4
sontang: 4
fee: 4
topang: 4
konstruksi: 4
manufaktur: 4
supply: 4
epi: 4
pph: 4
marketplace: 4
kuntadi: 4
ketidaksesuaian: 4
polri: 4
bapanas: 4
premium: 4
adaptif: 4
skd: 4
rini: 4
twk: 4
tiu: 4
karakteristik: 4
tkp: 4
aparatur: 4
reformasi: 4
pakar: 4
deret: 4
an: 4
frekuensi: 4
nonkonvensional: 4
det: 4
kira: 4
resources: 4
oki: 4
penandatanganan: 4
mumpuni: 4
budaya: 4
rel: 4
mas: 4
kredit: 4
perusahaanperusahaan: 4
gotong: 4
royong: 4
communication: 4
rusa: 4
revisi: 4
pemprov: 4
mezzanine: 4
djuanda: 4
anne: 4
kahar: 4
majeure: 4
efektivitas: 4
coo: 4
wifi: 4
perangkat: 4
populasi: 4
sam: 4
koreksi: 4
mncn: 4
pojk: 4
kementerianlembaga: 4
debottlenecking: 4
normal: 4
idola: 4
grain: 4
rice: 4
koki: 4
xii: 4
block: 4
regasifikasi: 4
bijih: 4
zein: 4
adcp: 4
banking: 4
aminuddin: 4
destinasi: 4
pondok: 4
kehatihatian: 4
defisit: 4
yoy: 4
wishlist: 4
blu: 4
metode: 4
agusman: 4
situs: 3
saudarasaudara: 3
saudara: 3
night: 3
streaming: 3
norman: 3
gunung: 3
school: 3
brunei: 3
asrama: 3
cerita: 3
serap: 3
best: 3
otot: 3
punggung: 3
noc: 3
banten: 3
tayang: 3
nur: 3
fajar: 3
tunggang: 3
kuda: 3
sendiri: 3
untuk: 3
berturutturut: 3
farhan: 3
ubaidillah: 3

In [13]:
# Buat DataFrame baru dengan isi asli, isi stemmed, dan kategori
processed_df = df[['isi_berita', 'stemmed_isi', 'kategori']].copy()

# Ganti nama kolom
processed_df.rename(columns={'stemmed_isi': 'hasil_preprocessing'}, inplace=True)

# Konversi frekuensi kata ke DataFrame
frequency_df = pd.DataFrame.from_dict(word_frequencies, orient='index', columns=['frequency'])
frequency_df.index.name = 'word'
frequency_df.sort_values(by='frequency', ascending=False, inplace=True)

# Simpan ke dua file CSV terpisah
processed_df.to_csv('hasil_preprocessing_berita.csv', index=False, encoding='utf-8')
frequency_df.to_csv('frekuensi_kata_berita.csv', encoding='utf-8')

print("Hasil preprocessing disimpan di 'hasil_preprocessing_berita.csv'")
print("Frekuensi kata disimpan di 'frekuensi_kata_berita.csv'")

Hasil preprocessing disimpan di 'hasil_preprocessing_berita.csv'
Frekuensi kata disimpan di 'frekuensi_kata_berita.csv'

In [14]:
hasil_preprocessing = "hasil_preprocessing_berita.csv"  
df = pd.read_csv(hasil_preprocessing)

# Tampilkan data
df

,isi_berita,hasil_preprocessing,kategori
0,Ketua UmumKomite Olahraga Nasional Indonesia (...,"['ketua', 'umumkomite', 'olahraga', 'nasional'...",Sport
1,Pengurus Pusat Kickboxing Indonesia (PP KBI)pe...,"['urus', 'pusat', 'kickboxing', 'indonesia', '...",Sport
2,"Lina Hisage, atlet tolak peluru asal Wamena, P...","['lina', 'hisage', 'atlet', 'tolak', 'peluru',...",Sport
3,Timnas Equestrian Indonesiasudah bertolak ke J...,"['timnas', 'equestrian', 'indonesiasudah', 'to...",Sport
4,Ciamis- Sebanyak 549 siswa dari 40 SD mengikut...,"['ciamis', 'siswa', 'sd', 'ikut', 'lomba', 'ol...",Sport
...,...,...,...
195,Direktorat Jenderal Bea dan Cukai (DJBC) Kemen...,"['direktorat', 'jenderal', 'bea', 'cukai', 'dj...",Finance
196,Ribuan pegawai Kementerian Pekerjaan Umum (PU)...,"['ribu', 'pegawai', 'menteri', 'kerja', 'pu', ...",Finance
197,Posisi Utang Luar Negeri (ULN) Indonesia pada ...,"['posisi', 'utang', 'negeri', 'uln', 'indonesi...",Finance
198,Otoritas Jasa Keuangan (OJK) akan meresmikan I...,"['otoritas', 'jasa', 'uang', 'ojk', 'resmi', '...",Finance
199,Direktorat Jenderal Bea dan Cukai (DJBC) Kemen...,"['direktorat', 'jenderal', 'bea', 'cukai', 'dj...",Finance

In [15]:
frekuensi_kata = "frekuensi_kata_berita.csv"  
df = pd.read_csv(frekuensi_kata)

# Tampilkan data
df

           word  frequency
0     indonesia        354
1       jakarta        268
2       menteri        194
3            to        189
4       content        187
...         ...        ...
5470      padan          1
5471     artoto          1
5472        din          1
5473     junica          1
5474      lisan          1

[5475 rows x 2 columns]